language: julia
os:
  - osx
  - linux
julia:
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
